SELECT e.nom FROM "employes.csv" e WHERE e.nom = e.nom ORDER BY e.nom DESC

(* Réponse : 
e.nom 
Zenaida Ashley	
Yuli Pate	
Yoshio Short	
Yen Perez	
Vivian Gregory	
Vernon Nieves	
Uta Lindsey	
Thor Bush	
Tatyana Becker	
Tana Thomas	
Tana Dillard	
Simon Oneill	
Ryan Hyde	
Rose Hancock	
Rebecca Carson	
Ray Tran	
Ray Atkins	
Raphael Diaz	
Philip Whitney	
Peter Steele	
Patrick Carey	
Paki Stanley	
Otto Gray	
Ora Grimes	
Olympia Gay	
Oliver Lowe	
Odysseus Joyce	
Norman Murphy	
Nichole Baldwin	
Nell Hurst	
Montana Mathis	
Mollie Poole	
Minerva Ray	
Melinda Lott	
McKenzie Jensen	
Maxwell Trujillo	
Martin Cabrera	
Marshall Nguyen	
Lillian Berg	
Kirby Washington	
Kieran Weaver	
Kessie Simmons	
Kerry Walton	
Kenyon Molina	
Kenyon Hood	
Kenneth Estrada	
Kelly Schneider	
Keelie Rosales	
Kameko Short	
Kai Kim	
Joelle Meyer	
Jillian Watson	
Jasper Griffin	
Ivy Carroll	
Iris Mcbride	
Iona Rasmussen	
Hyacinth Harris	
Hoyt Alston	
Hop White	
Honorato Bowman	
Hiram Bullock	
Heidi Vinson	
Hedwig Macias	
Hamish Fulton	
Guinevere Byers	
Gregory Hunter	
Giacomo Case	
Gemma Wells	
Gemma Calhoun	
Garth Chen	
Fredericka Alexander	
Forrest Harrison	
Evan Lynch	
Elmo Harrington	
Eliana Santos	
Diana Peterson	
Diana Levy	
Devin Bolton	
Destiny Love	
Deborah Noel	
Dante Pena	
Coby Dennis	
Clementine Santana	
Clarke Christian	
Clark Sanford	
Clark Henson	
Clark Hensley	
Carly Casey	
Carl Marquez	
Bruno Shepherd	
Brandon Travis	
Blaze Cooper	
Bernard Rice	
Austin Mueller	
Aristotle Lloyd	
Arden Lancaster	
Amir Wall	
Amelia Bryant	
Alexander Sullivan	
Aidan Livingston	*)
