SELECT e.nom AS name, e.ide AS identifiant FROM "employes.csv" e WHERE e.nom=e.nom ORDER BY e.name DESC, e.identifiant ASC

(* Réponse :
e.name e.identifiant 
Zenaida Ashley	37	
Yuli Pate	95	
Yoshio Short	10	
Yen Perez	56	
Vivian Gregory	48	
Vernon Nieves	57	
Uta Lindsey	43	
Thor Bush	91	
Tatyana Becker	17	
Tana Thomas	29	
Tana Dillard	11	
Simon Oneill	27	
Ryan Hyde	64	
Rose Hancock	12	
Rebecca Carson	77	
Ray Tran	25	
Ray Atkins	4	
Raphael Diaz	69	
Philip Whitney	16	
Peter Steele	63	
Patrick Carey	79	
Paki Stanley	3	
Otto Gray	5	
Ora Grimes	92	
Olympia Gay	30	
Oliver Lowe	22	
Odysseus Joyce	50	
Norman Murphy	100	
Nichole Baldwin	67	
Nell Hurst	6	
Montana Mathis	72	
Mollie Poole	42	
Minerva Ray	26	
Melinda Lott	52	
McKenzie Jensen	9	
Maxwell Trujillo	41	
Martin Cabrera	35	
Marshall Nguyen	68	
Lillian Berg	98	
Kirby Washington	87	
Kieran Weaver	14	
Kessie Simmons	13	
Kerry Walton	59	
Kenyon Molina	96	
Kenyon Hood	18	
Kenneth Estrada	85	
Kelly Schneider	47	
Keelie Rosales	60	
Kameko Short	78	
Kai Kim	82	
Joelle Meyer	34	
Jillian Watson	86	
Jasper Griffin	32	
Ivy Carroll	33	
Iris Mcbride	83	
Iona Rasmussen	45	
Hyacinth Harris	28	
Hoyt Alston	21	
Hop White	84	
Honorato Bowman	58	
Hiram Bullock	53	
Heidi Vinson	94	
Hedwig Macias	71	
Hamish Fulton	1	
Guinevere Byers	15	
Gregory Hunter	61	
Giacomo Case	20	
Gemma Wells	39	
Gemma Calhoun	7	
Garth Chen	24	
Fredericka Alexander	73	
Forrest Harrison	66	
Evan Lynch	99	
Elmo Harrington	44	
Eliana Santos	54	
Diana Peterson	55	
Diana Levy	36	
Devin Bolton	8	
Destiny Love	62	
Deborah Noel	81	
Dante Pena	49	
Coby Dennis	2	
Clementine Santana	89	
Clarke Christian	31	
Clark Sanford	51	
Clark Henson	76	
Clark Hensley	80	
Carly Casey	23	
Carl Marquez	97	
Bruno Shepherd	38	
Brandon Travis	19	
Blaze Cooper	75	
Bernard Rice	90	
Austin Mueller	65	
Aristotle Lloyd	74	
Arden Lancaster	88	
Amir Wall	40	
Amelia Bryant	93	
Alexander Sullivan	70	
Aidan Livingston	46 *)
