SELECT e.nom FROM "employes.csv" e WHERE e.nom=e.nom

(* Réponse :
e.nom 
Norman Murphy	
Evan Lynch	
Lillian Berg	
Carl Marquez	
Kenyon Molina	
Yuli Pate	
Heidi Vinson	
Amelia Bryant	
Ora Grimes	
Thor Bush	
Bernard Rice	
Clementine Santana	
Arden Lancaster	
Kirby Washington	
Jillian Watson	
Kenneth Estrada	
Hop White	
Iris Mcbride	
Kai Kim	
Deborah Noel	
Clark Hensley	
Patrick Carey	
Kameko Short	
Rebecca Carson	
Clark Henson	
Blaze Cooper	
Aristotle Lloyd	
Fredericka Alexander	
Montana Mathis	
Hedwig Macias	
Alexander Sullivan	
Raphael Diaz	
Marshall Nguyen	
Nichole Baldwin	
Forrest Harrison	
Austin Mueller	
Ryan Hyde	
Peter Steele	
Destiny Love	
Gregory Hunter	
Keelie Rosales	
Kerry Walton	
Honorato Bowman	
Vernon Nieves	
Yen Perez	
Diana Peterson	
Eliana Santos	
Hiram Bullock	
Melinda Lott	
Clark Sanford	
Odysseus Joyce	
Dante Pena	
Vivian Gregory	
Kelly Schneider	
Aidan Livingston	
Iona Rasmussen	
Elmo Harrington	
Uta Lindsey	
Mollie Poole	
Maxwell Trujillo	
Amir Wall	
Gemma Wells	
Bruno Shepherd	
Zenaida Ashley	
Diana Levy	
Martin Cabrera	
Joelle Meyer	
Ivy Carroll	
Jasper Griffin	
Clarke Christian	
Olympia Gay	
Tana Thomas	
Hyacinth Harris	
Simon Oneill	
Minerva Ray	
Ray Tran	
Garth Chen	
Carly Casey	
Oliver Lowe	
Hoyt Alston	
Giacomo Case	
Brandon Travis	
Kenyon Hood	
Tatyana Becker	
Philip Whitney	
Guinevere Byers	
Kieran Weaver	
Kessie Simmons	
Rose Hancock	
Tana Dillard	
Yoshio Short	
McKenzie Jensen	
Devin Bolton	
Gemma Calhoun	
Nell Hurst	
Otto Gray	
Ray Atkins	
Paki Stanley	
Coby Dennis	
Hamish Fulton	*)
