SELECT e.nom AS emp, d.nom AS dpt FROM "employes.csv" e, "departements.csv" d WHERE e.dpt = d.idd ORDER BY e.emp

(* Réponse :
d.dpt e.emp 
Administration	Alexander Sullivan	
Comptabilité	Amelia Bryant	
Comptabilité	Amir Wall	
Marketing	Arden Lancaster	
Exportations	Aristotle Lloyd	
Direction	Austin Mueller	
Développement	Bernard Rice	
Achats	Brandon Travis	
Développement	Bruno Shepherd	
Marketing	Carly Casey	
Marketing	Clark Hensley	
Direction	Clark Henson	
Production	Clark Sanford	
Développement	Clarke Christian	
Marketing	Clementine Santana	
Comptabilité	Coby Dennis	
Achats	Dante Pena	
Exportations	Deborah Noel	
RH	Destiny Love	
Direction	Devin Bolton	
Marketing	Diana Levy	
Recherche	Diana Peterson	
Direction	Eliana Santos	
Marketing	Elmo Harrington	
Recherche	Forrest Harrison	
Direction	Fredericka Alexander	
Marketing	Garth Chen	
Direction	Gemma Calhoun	
Exportations	Gemma Wells	
Comptabilité	Giacomo Case	
Production	Gregory Hunter	
Développement	Guinevere Byers	
Direction	Hamish Fulton	
Exportations	Hedwig Macias	
Comptabilité	Heidi Vinson	
Comptabilité	Hiram Bullock	
Exportations	Honorato Bowman	
RH	Hop White	
Administration	Hoyt Alston	
Production	Hyacinth Harris	
Direction	Iris Mcbride	
Marketing	Ivy Carroll	
Comptabilité	Jasper Griffin	
Production	Jillian Watson	
Achats	Joelle Meyer	
Marketing	Kai Kim	
Direction	Kameko Short	
Comptabilité	Keelie Rosales	
Marketing	Kelly Schneider	
Comptabilité	Kenneth Estrada	
Recherche	Kenyon Hood	
Production	Kenyon Molina	
Marketing	Kerry Walton	
Achats	Kessie Simmons	
Direction	Kieran Weaver	
RH	Kirby Washington	
Recherche	Lillian Berg	
Développement	Marshall Nguyen	
Développement	Martin Cabrera	
Achats	Maxwell Trujillo	
Direction	McKenzie Jensen	
Administration	Melinda Lott	
Marketing	Minerva Ray	
Production	Mollie Poole	
Développement	Montana Mathis	
Comptabilité	Nell Hurst	
Marketing	Nichole Baldwin	
Comptabilité	Norman Murphy	
Recherche	Oliver Lowe	
Exportations	Olympia Gay	
Recherche	Ora Grimes	
Achats	Otto Gray	
RH	Paki Stanley	
Production	Patrick Carey	
Marketing	Peter Steele	
Production	Philip Whitney	
RH	Raphael Diaz	
Production	Ray Atkins	
Administration	Ray Tran	
Achats	Rebecca Carson	
RH	Rose Hancock	
Marketing	Ryan Hyde	
Marketing	Simon Oneill	
Comptabilité	Tana Dillard	
Direction	Tana Thomas	
Administration	Tatyana Becker	
Direction	Thor Bush	
RH	Uta Lindsey	
Recherche	Vernon Nieves	
Direction	Vivian Gregory	
Marketing	Yen Perez	
Marketing	Yoshio Short	
Développement	Yuli Pate	
RH	Zenaida Ashley	*)
