SELECT e.nom AS emp, d.nom AS dpt FROM "employes.csv" e, "departements.csv" d WHERE e.dpt = d.idd ORDER BY d.dpt

(* Réponse :
d.dpt e.emp 
Achats	Rebecca Carson	
Achats	Dante Pena	
Achats	Maxwell Trujillo	
Achats	Joelle Meyer	
Achats	Brandon Travis	
Achats	Kessie Simmons	
Achats	Otto Gray	
Administration	Alexander Sullivan	
Administration	Melinda Lott	
Administration	Ray Tran	
Administration	Hoyt Alston	
Administration	Tatyana Becker	
Comptabilité	Norman Murphy	
Comptabilité	Heidi Vinson	
Comptabilité	Amelia Bryant	
Comptabilité	Kenneth Estrada	
Comptabilité	Keelie Rosales	
Comptabilité	Hiram Bullock	
Comptabilité	Amir Wall	
Comptabilité	Jasper Griffin	
Comptabilité	Giacomo Case	
Comptabilité	Tana Dillard	
Comptabilité	Nell Hurst	
Comptabilité	Coby Dennis	
Direction	Thor Bush	
Direction	Iris Mcbride	
Direction	Kameko Short	
Direction	Clark Henson	
Direction	Fredericka Alexander	
Direction	Austin Mueller	
Direction	Eliana Santos	
Direction	Vivian Gregory	
Direction	Tana Thomas	
Direction	Kieran Weaver	
Direction	McKenzie Jensen	
Direction	Devin Bolton	
Direction	Gemma Calhoun	
Direction	Hamish Fulton	
Développement	Yuli Pate	
Développement	Bernard Rice	
Développement	Montana Mathis	
Développement	Marshall Nguyen	
Développement	Bruno Shepherd	
Développement	Martin Cabrera	
Développement	Clarke Christian	
Développement	Guinevere Byers	
Exportations	Deborah Noel	
Exportations	Aristotle Lloyd	
Exportations	Hedwig Macias	
Exportations	Honorato Bowman	
Exportations	Gemma Wells	
Exportations	Olympia Gay	
Marketing	Clementine Santana	
Marketing	Arden Lancaster	
Marketing	Kai Kim	
Marketing	Clark Hensley	
Marketing	Nichole Baldwin	
Marketing	Ryan Hyde	
Marketing	Peter Steele	
Marketing	Kerry Walton	
Marketing	Yen Perez	
Marketing	Kelly Schneider	
Marketing	Elmo Harrington	
Marketing	Diana Levy	
Marketing	Ivy Carroll	
Marketing	Simon Oneill	
Marketing	Minerva Ray	
Marketing	Garth Chen	
Marketing	Carly Casey	
Marketing	Yoshio Short	
Production	Kenyon Molina	
Production	Jillian Watson	
Production	Patrick Carey	
Production	Gregory Hunter	
Production	Clark Sanford	
Production	Mollie Poole	
Production	Hyacinth Harris	
Production	Philip Whitney	
Production	Ray Atkins	
RH	Kirby Washington	
RH	Hop White	
RH	Raphael Diaz	
RH	Destiny Love	
RH	Uta Lindsey	
RH	Zenaida Ashley	
RH	Rose Hancock	
RH	Paki Stanley	
Recherche	Lillian Berg	
Recherche	Ora Grimes	
Recherche	Forrest Harrison	
Recherche	Vernon Nieves	
Recherche	Diana Peterson	
Recherche	Oliver Lowe	
Recherche	Kenyon Hood	*)
